version: '3.8'

services:
  api01:
    image: backend-java:latest
    build:
      context: ./
      dockerfile: backend-java/Dockerfile
    hostname: api01
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150MB"

  api02:
    image: backend-java:latest
    build:
      context: ./
      dockerfile: backend-java/Dockerfile
    hostname: api02
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8082:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150MB"

  react-app:
    build:
      context: ./
      dockerfile: frontend-react/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api01
      - api02
    deploy:
      resources: {}

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
      - react-app
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./backend-java/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "200MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
