server:
  servlet:
    context-path: /api
spring:
  application:
    name: backend-java
  datasource:
    url: jdbc:postgresql://localhost:5432/rinha-backend
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
  sql:
    init:
      mode: never